Repository tigera/docs, pull requests merged in 2023-07, with the labels that each got.

#793 DOCS-Windows-policy-recommendations
  calico-enterprise/network-policy/recommendations/policy-recommendations.mdx
  calico-enterprise_versioned_docs/version-3.17/network-policy/recommendations/policy-recommendations.mdx
Labels: [DON'T MERGE]

#774 fix VPP ipsec docs & add troubleshooting info
  calico/getting-started/kubernetes/vpp/ipsec.mdx
Labels: Needs docs review

#836 GH835: adds CRD update step to helm update instructions
  calico/operations/upgrading/kubernetes-upgrade.mdx
  calico_versioned_docs/version-3.24/operations/upgrading/kubernetes-upgrade.mdx
  calico_versioned_docs/version-3.25/operations/upgrading/kubernetes-upgrade.mdx
  calico_versioned_docs/version-3.26/operations/upgrading/kubernetes-upgrade.mdx
Labels: Needs docs review, community-contributor
