Repository tigera/docs, pull requests merged in 2023-06, with the labels that each got.

#644 [3.18] BPF Additional Felix configuration parameter for bpfDisableGROForIfaces
  calico-cloud/reference/resources/felixconfig.mdx
  calico-enterprise/reference/resources/felixconfig.mdx
  calico/reference/resources/felixconfig.mdx
Labels: Ready for release

#720 DOCS-1542: Adds link to knowledge base on CC support page
  calico-cloud/get-help/support.mdx
  calico-cloud_versioned_docs/version-3.16/get-help/support.mdx
  calico-cloud_versioned_docs/version-3.17/get-help/support.mdx
Labels: WIP

#630 [3.16.3] Update EGW docs for auto-detection - 3.16
  calico-enterprise_versioned_docs/version-3.16/networking/egress/egress-gateway-aws.mdx
  calico-enterprise_versioned_docs/version-3.16/networking/egress/egress-gateway-azure.mdx
  calico-enterprise_versioned_docs/version-3.16/networking/egress/egress-gateway-on-prem.mdx
Labels: Ready for release

#704 DOCS-1428: CE-Support-3.17.0
  calico-enterprise/getting-started/compatibility.mdx
  calico-enterprise_versioned_docs/version-3.17/getting-started/compatibility.mdx
Labels: dependencies, WIP
